name: DL

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4,16 * * *'

env:
  MACHINE: misc2

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      DIR_KIND: ${{ matrix.kind }}
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        kind:
          - 3x3_unreadable
          - athletevideos
          - callinshow
          - daxflame
          - dwu
          - fds
          - gundomirei
          - hikakintv
          - himarichannel
          - ikine
          - ionlead
          - ixy
          - kataokamiyu
          - kemikaru
          - kikurin
          - kizunaai
          - marsdenit
          - miraiakari
          - miyasako
          - mtrokk
          - nakagawashoko
          - nakamurakazunori
          - namahoshi
          - nao2d8x
          - ohishiaki
          - pookumano
          - pregshotonly
          - setsu
          - takeiteasy
          - tsukinomito
          - ychannelgsv
          - yesbabylisa
          - yukihanalamy
    steps:
      - uses: actions/checkout@v2
      - name: Set up Tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: "1.18.1"
      - name: Add SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan "$(tailscale ip -6 $MACHINE)" >> ~/.ssh/known_hosts
          printf "%s" "$SSH_KEY" > ~/.ssh/key
          chmod 600 ~/.ssh/key
      - name: Set up mandantory commands and install config
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y ffmpeg
          sudo rm -rf /usr/share/dotnet || true
          wget -O ~/ia https://archive.org/download/ia-pex/ia
          wget -O ~/yt-dlp https://github.com/ytdl-patched/ytdl-patched/releases/latest/download/youtube-dl
          chmod a+x ~/ia ~/yt-dlp
          mkdir -p ~/.config/
          rsync -as -e "ssh -i $HOME/.ssh/key" lesmi@"[$(tailscale ip -6 $MACHINE)]":.config/ia.ini.bdmv ~/.config/ia.ini
          # rsync -as -e "ssh -i $HOME/.ssh/key" lesmi@"[$(tailscale ip -6 $MACHINE)]":ck.txt ~/ck.txt
          rsync -as -e "ssh -i $HOME/.ssh/key" lesmi@"[$(tailscale ip -6 $MACHINE)]":internet_archive/"${{ matrix.kind }}" .
          cp *.conf ~/
          ~/yt-dlp --verbose || true
      - name: Run task
        working-directory: ${{ matrix.kind }}
        run: ./dl.sh

  post:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: "1.18.1"
      - name: Add SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan "$(tailscale ip -6 $MACHINE)" >> ~/.ssh/known_hosts
          printf "%s" "$SSH_KEY" > ~/.ssh/key
          chmod 600 ~/.ssh/key
      - name: Create a save point
        run: |
          ssh -i $HOME/.ssh/key lesmi@"$(tailscale ip -6 $MACHINE)" bash -xec 'cd ~/internet_archive && ./save.sh'
    
