name: DL

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4,12,20 * * *'

env:
  MACHINE: misc2
  MACHINE_KEY: https://git.io/JStgk

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: "1.18.1"
      - name: Set up
        id: setup
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh ./ia/
          wget -qO- $MACHINE_KEY >> ~/.ssh/known_hosts
          printf "%s" "$SSH_KEY" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          sudo apt install -y sshfs
          sshfs -o IdentityFile=$HOME/.ssh/key lesmi@"[$(tailscale ip -6 $MACHINE)]":internet_archive/ ./ia/
          cd ia/
          echo "::set-output name=matrix::$(./enumerate.sh)"

  build:
    needs: [setup]
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      DIR_KIND: ${{ matrix.kind }}
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        kind: ${{ fromJson(needs.setup.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: "1.18.1"
      - name: Add SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          wget -qO- $MACHINE_KEY >> ~/.ssh/known_hosts
          printf "%s" "$SSH_KEY" > ~/.ssh/key
          chmod 600 ~/.ssh/key
      - name: Erase everything unnessesarily eating much space
        continue-on-error: true
        run: |
          wget https://github.com/ZZROTDesign/docker-clean/raw/master/docker-clean -O docker-clean
          curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
          chmod a+x docker-clean n
          sudo ./docker-clean all
          yes | sudo ./n uninstall
          sudo systemctl stop docker.service snapd.service snapd.socket
          sudo umount -l /snap/*/*/ || true
          sudo rm -rf docker-clean n /usr/share/dotnet/ /usr/lib/mono/ \
            "$ANDROID_SDK_ROOT" /opt/hostedtoolcache/ /var/lib/docker/ \
            "$CONDA" "$SELENIUM_JAR_PATH" "$NVM_DIR" btrfs-progs/ \
            /var/lib/snapd/ /snap/ || true
          sudo apt autoremove -y firefox google-chrome-stable build-essential \
            *dotnet* g{cc,++} *libboost* gfortran* google-cloud-sdk gnupg* \
            hhvm  fuse-overlayfs gh git-lfs git-ftp *dotnet* *aspnetcore* aria2 \
            brotli *mono* *clang* php* r-* skopeo mediainfo moby-* mongodb-* \
            mysql-* p7zip* nginx apache2 openjdk-* adoptopenjdk-* temurin-* \
            ant* snapd libudev-dev liblzo2-dev uuid-dev libblkid-dev comerr-dev \
            libext2fs-dev automake || true
      - name: Set up mandantory commands and install config
        run: |
          sudo apt update
          sudo apt install -y wget sshfs
          wget -O ~/ia https://archive.org/download/ia-pex/ia || (rm -f ~/ia && brew install internetarchive && ln -s $(which ia) ~/ia )
          wget -O ~/yt-dlp https://github.com/ytdl-patched/ytdl-patched/releases/latest/download/youtube-dl
          wget -qO- https://github.com/ytdl-patched/FFmpeg-Builds/releases/download/latest/ffmpeg-n5.0-latest-linux64-nonfree-5.0.tar.xz | tar --strip-components=1 -C /usr/ -xJf - || true
          if ! which ffmpeg ; then
            echo "::warning::Failed to detect ffmpeg installation. Falling back to apt install"
            sudo apt install -y ffmpeg
          fi
          chmod a+x ~/ia ~/yt-dlp
          mkdir -p ~/.config/ ./ia
          rsync -e "ssh -i $HOME/.ssh/key" lesmi@"[$(tailscale ip -6 $MACHINE)]":.config/ia.ini.bdmv ~/.config/ia.ini
          # rsync -e "ssh -i $HOME/.ssh/key" lesmi@"[$(tailscale ip -6 $MACHINE)]":ck.txt ~/ck.txt
          # rsync -r -e "ssh -i $HOME/.ssh/key" lesmi@"[$(tailscale ip -6 $MACHINE)]":internet_archive/"${{ matrix.kind }}" .
          sshfs -o IdentityFile=$HOME/.ssh/key lesmi@"[$(tailscale ip -6 $MACHINE)]":internet_archive/ ./ia/
          ./ia/secret.sh || true
          cp *.conf ~/
      - name: Check application versions
        run: |
          ~/yt-dlp --verbose || true
      - name: Run task
        working-directory: ia/${{ matrix.kind }}
        run: |
          sha256sum archive.txt || true
          touch /tmp/download-stderr
          tail -f /tmp/download-stderr &
          ./dl.sh 2>/tmp/download-stderr
          sha256sum archive.txt || true
      - name: Show error log
        continue-on-error: true
        working-directory: ia/${{ matrix.kind }}
        if: ${{ 0 == 0 || success() || failure() }}
        run: cat /tmp/download-stderr


  post:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: "1.18.1"
      - name: Add SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          wget -qO- $MACHINE_KEY >> ~/.ssh/known_hosts
          printf "%s" "$SSH_KEY" > ~/.ssh/key
          chmod 600 ~/.ssh/key
      - name: Create a save point
        run: |
          echo 'cd ~/internet_archive && ./save.sh' | ssh -i $HOME/.ssh/key lesmi@"$(tailscale ip -6 $MACHINE)" bash
