name: DL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MACHINE: misc2
      DIR_KIND: ${{ matrix.kind }}
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        kind:
          - 3x3_unreadable
          - athletevideos
          - callinshow
          - fds
          - hikakintv
          - himarichannel
          - ionlead
          - kemikaru
          - kikurin
          - kizunaai
          - mtrokk
          - nao2d8x
          - ohishiaki
          - pookumano
          - setsu
          - takeiteasy
          - ychannelgsv
    steps:
      - uses: actions/checkout@v2
      - name: Set up Tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: "1.16.1"
      - name: Add SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan "$(tailscale ip -6 $MACHINE)" >> ~/.ssh/known_hosts
          printf "%s" "$SSH_KEY" > ~/.ssh/key
          chmod 600 ~/.ssh/key
      - name: Set up mandantory commands and install config
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y ffmpeg
          wget -O ~/ia https://archive.org/download/ia-pex/ia
          wget -O ~/yt-dlp https://bookish-octo-barnacle.vercel.app/api/release/latest/youtube-dl
          chmod a+x ~/ia ~/yt-dlp
          mkdir -p ~/.config/
          rsync -as -e "ssh -i $HOME/.ssh/key" lesmi@"[$(tailscale ip -6 $MACHINE)]":.config/ia.ini.orig ~/.config/ia.ini
          # rsync -as -e "ssh -i $HOME/.ssh/key" lesmi@"[$(tailscale ip -6 $MACHINE)]":ck.txt ~/ck.txt
          rsync -as -e "ssh -i $HOME/.ssh/key" lesmi@"[$(tailscale ip -6 $MACHINE)]":internet_archive/"${{ matrix.kind }}" .
          cp *.conf ~/
          ~/yt-dlp --verbose || true
      - name: Run task
        working-directory: ${{ matrix.kind }}
        run: ./dl.sh
          
