name: Probe current environment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: apt list --installed
      - run: apt list --installed | grep -v automatic
      - name: path of some commands
        run: |
          whereis helm ant gradle lerna maven sbt ansible apt-fast azcopy bazel \
            java bazelisk bicep buildah cmake docker docker-compose fastlane haveged heroku heroku-cli \
            hhvm kubectl kustomize leningen mediainfo mercurial minikube n newman nvm parcel \
            podman polumi r skeopeo svn terraform-cli yamllint yq zstd \
            alibaba{,-}{,cloud}{,-cli} aws-cli gh gcloud hub netlify{,-cli} openshift \
            oras vercel {google-,}chrome{,-stable,.canary} firefox
      - run: df -h
      - name: Erase everything unnessesarily easting much space
        continue-on-error: true
        run: |
          sudo rm -rf /usr/share/dotnet/ /usr/lib/mono/ || true
          sudo apt autoremove -y firefox google-chrome-stable build-essential \
            *dotnet* g{cc,++}* *libboost* gfortran* google-cloud-sdk gnupg* \
            hhvm  fuse-overlayfs gh git-lfs git-ftp *dotnet* *aspnetcore* aria2 \
            brotli *mono* *clang* || true
      - run: df -h
