name: Probe current environment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: apt list --installed
      - run: apt list --installed | grep -v automatic
      - run: ls /home/linuxbrew/.linuxbrew/Cellar/
      - name: path of some commands
        run: |
          whereis helm ant gradle lerna maven sbt ansible apt-fast azcopy bazel \
            java bazelisk bicep buildah cmake docker docker-compose fastlane haveged heroku heroku-cli \
            hhvm kubectl kustomize leningen mediainfo mercurial minikube n newman nvm parcel \
            podman polumi r skeopeo svn terraform-cli yamllint yq zstd \
            alibaba{,-}{,cloud}{,-cli} aws-cli gh gcloud hub netlify{,-cli} openshift \
            oras vercel {google-,}chrome{,-stable,.canary} firefox
          echo "$ANDROID_SDK_ROOT" "$CONDA" "$SELENIUM_JAR_PATH" "$NVM_DIR"
      - run: df -h
      - name: Attempt making more space
        continue-on-error: true
        run: |
          mount
          sudo swapoff -a
          sudo umount /boot/efi /mnt
          sudo wipefs /dev/sda?* /dev/sda
          sudo btrfs-convert /dev/sdb1
          sudo btrfstune -U 39bd9ac9-1b8c-487c-85b0-5b4726f12ada /dev/sdb1
          sudo remount / -t btrfs
      - name: Erase everything unnessesarily eating much space
        continue-on-error: true
        run: |
          wget https://github.com/ZZROTDesign/docker-clean/raw/master/docker-clean -O docker-clean
          curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
          chmod a+x docker-clean n
          sudo ./docker-clean all
          yes | sudo ./n uninstall
          sudo systemctl stop docker.service snapd.service snapd.socket
          sudo umount -l /snap/*/*/ || true
          sudo rm -rf docker-clean n /usr/share/dotnet/ /usr/lib/mono/ \
            "$ANDROID_SDK_ROOT" /opt/hostedtoolcache/ /var/lib/docker/ \
            "$CONDA" "$SELENIUM_JAR_PATH" "$NVM_DIR" \
            /var/lib/snapd/ /snap/ || true
          sudo apt autoremove -y firefox google-chrome-stable build-essential \
            *dotnet* g{cc,++} *libboost* gfortran* google-cloud-sdk gnupg* \
            hhvm  fuse-overlayfs gh git-lfs git-ftp *dotnet* *aspnetcore* aria2 \
            brotli *mono* *clang* php* r-* skopeo mediainfo moby-* mongodb-* \
            mysql-* p7zip* nginx apache2 openjdk-* adoptopenjdk-* temurin-* \
            ant* snapd || true
      - run: df -h
      - run: python3 -V
