name: Probe current environment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: apt list --installed
      - run: apt list --installed | grep -v automatic
      - run: ls /home/linuxbrew/.linuxbrew/Cellar/
      - name: path of some commands
        run: |
          whereis helm ant gradle lerna maven sbt ansible apt-fast azcopy bazel \
            java bazelisk bicep buildah cmake docker docker-compose fastlane haveged heroku heroku-cli \
            hhvm kubectl kustomize leningen mediainfo mercurial minikube n newman nvm parcel \
            podman polumi r skeopeo svn terraform-cli yamllint yq zstd \
            alibaba{,-}{,cloud}{,-cli} aws-cli gh gcloud hub netlify{,-cli} openshift \
            oras vercel {google-,}chrome{,-stable,.canary} firefox
      - run: df -h
      - name: Erase everything unnessesarily eating much space
        continue-on-error: true
        run: |
          wget https://github.com/ZZROTDesign/docker-clean/raw/master/docker-clean -O docker-clean
          curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
          chmod a+x docker-clean n
          sudo ./docker-clean all
          yes | sudo ./n uninstall
          sudo rm -rf docker-clean n /usr/share/dotnet/ /usr/lib/mono/ \
            "$ANDROID_ROOT" /opt/hostedtoolcache/ \
            "$CONDA" "$SELENIUM_JAR_NAME" "$NVM_DIR" || true
          sudo systemctl stop docker.service
          sudo apt autoremove -y firefox google-chrome-stable build-essential \
            *dotnet* g{cc,++} *libboost* gfortran* google-cloud-sdk gnupg* \
            hhvm  fuse-overlayfs gh git-lfs git-ftp *dotnet* *aspnetcore* aria2 \
            brotli *mono* *clang* php* r-* skopeo mediainfo moby-* mongodb-* \
            mysql-* p7zip* nginx apache2 openjdk-* adoptopenjdk-* temurin-* \
            ant* || true
      - run: df -h
      - run: python3 -V
